// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmcwyigpnxjmcehfphxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtY3d5aWdwbnhqbWNlaGZwaHhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTMwNTUsImV4cCI6MjA3MzUyOTA1NX0.Jon2AJGwlBisb51hNDF7IisQW_9j-EyEEoyGNEDFGIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});